---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: jumpbox-deployment
- name: stemcell-aws
- name: stemcell-azure
- name: stemcell-gcp
- name: stemcell-openstack
- name: stemcell-vsphere

outputs:
- name: updated-jumpbox-deployment

run:
  path: jumpbox-deployment/ci/tasks/bump-stemcell.sh
